name: Build and test workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-13
    # https://github.com/actions/virtual-environments/blob/main/images/macos/macos-13-Readme.md
    # target macOS 12.4 isn't supported in default Xcode for macOS 12
    # - default Xcode version is 14.3.1 for macos-13 builder image

    #strategy:
    #  matrix:
    #    run-config:
    #      - { scheme: 'SPISearch', destination: 'platform=macOS' }
    #      - { scheme: 'SPISearch', destination: 'platform=iOS Simulator,OS=15.2,name=iPhone 8' }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode 15.2
        run: sudo xcode-select -s /Applications/Xcode_15.2.app

      # env:
      #  DEVELOPER_DIR: /Applications/Xcode_15.2.app/Contents/Developer
      #- name: Show what's in Applications
      #  run: ls -al /Applications

      - name: Show Build Version
        run: xcodebuild -version

      #- name: Show Build Settings
      #  run: xcodebuild -showBuildSettings

      - name: Show Build SDK
        run: xcodebuild -showsdks
      # iOS 16.4, macOS 13.3 on macOS-13 w/ Xcode 13.4.1
      # iOS 17.0.1, iOS 17.2, macOS 13.3 on macOS-13 w/ Xcode 15.2

      - name: Show Destinations
        run: xcodebuild -showdestinations -scheme 'MeetingNotes'

      - name: Show Test Plans
        run: xcodebuild -showTestPlans -scheme 'MeetingNotes'

      #- name: iOS xcodebuild basic invoke
      #  run: xcodebuild clean test -scheme 'MeetingNotes'

      - name: iOS build for MeetingNotes
        # Xcode 15.2 settings
        run: xcodebuild clean build -scheme 'MeetingNotes' -destination 'platform=iOS Simulator,OS=17.0.1,name=iPhone 14' -sdk iphonesimulator17.2 -showBuildTimingSummary

      - name: iOS test
        # Xcode 15.2 settings
        run: xcodebuild test -scheme 'MeetingNotes' -testPlan 'MeetingNotes' -destination 'platform=iOS Simulator,OS=17.0.1,name=iPhone 14' -sdk iphonesimulator17.2 -showBuildTimingSummary

      - name: macOS build for MeetingNotes
        # Xcode 15.2 settings
        run: xcodebuild clean build -scheme 'MeetingNotes' -destination 'platform=macOS' -sdk macosx14.2 -showBuildTimingSummary

# w/ Xcode 14 beta 3:
# Local: xcodebuild clean test -scheme 'MeetingNotes' -destination 'platform=iOS Simulator,OS=16.0,name=iPhone 8' -sdk iphonesimulator16.0
# w/ Xcode 15.3 beta 2
#xcodebuild clean test -scheme 'MeetingNotes' -destination 'platform=iOS Simulator,OS=17.2,name=iPhone 15' -sdk iphonesimulator17.2

#export DEVELOPER_DIR=/Applications/Xcode.app
#xcodebuild clean test -scheme 'MeetingNotes' -destination 'platform=iOS Simulator,OS=17.2,name=iPhone 15' -sdk iphonesimulator17.2
